abstract: Simple interface to Locale::Maketext::Lexicon
author: Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.62
license: perl
name: Locale-Maketext-Simple
no_index: 
  directory: 
    - inc
    - t
version: 0.14
