abstract: Simple interface to Locale::Maketext::Lexicon
author: Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.64
license: MIT
name: Locale-Maketext-Simple
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.004
version: 0.18
